### ISSUE TITLE
ERROR: addChildDialog

### ISSUE THREAD

**Issue by msubglb** [afarooqui98/ECS193a#169]
The following error message is observed when I try to add the objects.

Traceback (most recent call last):
  File "***gem5/gem5_GUI/gui_views/catalog_view.py", line 112, in createSymObject
    dialog = addChildDialog("Add " + name + " as child of " + \
NameError: name 'addChildDialog' is not defined
Traceback (most recent call last):
  File "***gem5/gem5_GUI/gui_views/catalog_view.py", line 112, in createSymObject
    dialog = addChildDialog("Add " + name + " as child of " + \
NameError: name 'addChildDialog' is not defined

Any insights into the potential issues will be appreciated. Thanks

**Comment by makksi** [comment]
same issue for me
